### ISSUE TITLE
ValueError: Configurable 'infer_model' doesn't have a parameter named 'input_filename'

### ISSUE THREAD

**Issue by zhaozj89** [ElementalCognition/glucose#4]
I came across this problem when running `t5_scripts/model-test_run_decode_glucose.sh`. The customized [t5](https://github.com/ElementalCognition/text-to-text-transfer-transformer) seems not to work. Could you provide the environment `requirements.txt` file or the versions of dependencies? Thanks.

**Comment by orbiran** [comment]
Did you install T5 on the GCP as described in the readme? you shouldn't have to install any additional dependencies

**Comment by zhaozj89** [comment]
Yes. I used your customized [T5](https://github.com/ElementalCognition/text-to-text-transfer-transformer) on GCP. But I found some dependencies in https://github.com/ElementalCognition/text-to-text-transfer-transformer/blob/master/setup.py do not have specific versions, such as `tfds-nightly`, and did not make it work. Thanks anyway. I switched to the huggingface T5 as mentioned [here](https://github.com/ElementalCognition/glucose/issues/2#issuecomment-882545981).
